apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-prometheus
  namespace: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-prometheus
  template:
    metadata:
      labels:
        app: simple-prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.45.0
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: shared
spec:
  selector:
    app: simple-prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP