apiVersion: v1
kind: Namespace
metadata:
  name: visualizer
  labels:
    name: visualizer
---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-engineering
  labels:
    name: chaos-engineering
---
apiVersion: v1
kind: Namespace
metadata:
  name: cost-optimization
  labels:
    name: cost-optimization
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    name: security
---
apiVersion: v1
kind: Namespace
metadata:
  name: performance
  labels:
    name: performance
---
apiVersion: v1
kind: Namespace
metadata:
  name: shared
  labels:
    name: shared