apiVersion: v1
kind: ConfigMap
metadata:
  name: security-html
  namespace: security
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Security Posture Scanner</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #333; }
        .card { border: 1px solid #ddd; padding: 20px; margin: 20px 0; border-radius: 5px; }
        .high { color: red; font-weight: bold; }
        .medium { color: orange; }
        .low { color: green; }
      </style>
    </head>
    <body>
      <h1>Security Posture Scanner</h1>
      
      <div class="card">
        <h2>Security Scan Results</h2>
        <p>Last scan: March 6, 2025 19:30:45</p>
        <h3>Vulnerabilities Found:</h3>
        <ul>
          <li class="high">HIGH: Privileged container detected in pod nginx-pod (default namespace)</li>
          <li class="medium">MEDIUM: No resource limits defined in deployment frontend (visualizer namespace)</li>
          <li class="medium">MEDIUM: Latest image tag used in deployment backend (visualizer namespace)</li>
        </ul>
      </div>
      
      <div class="card">
        <h2>Compliance Status</h2>
        <p>CIS Kubernetes Benchmark: 85% compliant</p>
        <p>Pod Security Standards: 78% compliant</p>
      </div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-scanner
  namespace: security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-scanner
  template:
    metadata:
      labels:
        app: security-scanner
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: security-html
---
apiVersion: v1
kind: Service
metadata:
  name: security-scanner
  namespace: security
spec:
  selector:
    app: security-scanner
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: security-scanner-direct
  namespace: security
spec:
  selector:
    app: security-scanner
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082
  type: NodePort