apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-engineering
  namespace: chaos-engineering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-engineering
  template:
    metadata:
      labels:
        app: chaos-engineering
    spec:
      serviceAccountName: chaos-engineering-sa
      containers:
      - name: chaos-engineering
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: chaos-html
          mountPath: /usr/share/nginx/html
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
      - name: chaos-html
        configMap:
          name: chaos-html-content